### ISSUE TITLE
Driver.py obstacle avoidance error

### ISSUE THREAD

**Issue by isaacspokes** [romano-w/red-light-green-light-robot#21]
@romano-w  There is an issue in the [wall follow section](https://github.com/romano-w/red-light-green-light-robot/blob/36e7c35494d77796c733909b6117e44d9a286000/driver.py#L162)

I think we need to pass in an error here but I don't know what the error should be. Can you check your wall follow code

**Comment by romano-w** [comment]
Fixed the obstacle detection and driver problems
